---
name: rebase-command

on:
  repository_dispatch:
    types:
      rebase-command

jobs:
  rebase:
    if: github.event.client_payload.pull_request.rebaseable == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MYSECRET }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0

      - name: Rebase
        uses: peter-evans/rebase@v1
        with:
          token: ${{ secrets.MYSECRET }}
          repository: ${{ github.event.client_payload.pull_request.base.repo.full_name }}

      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.MYSECRET }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Pull request successfully rebased
          reaction-type: hooray

